### ISSUE TITLE
Support for UTF-8-BOM

### ISSUE THREAD

**Issue by davidski** [hadley/readr#263]
Reviewing #208 and #40, it looks like `readr` should support this, but the CRANed 0.1.1 is failing to handle a UTF-8-BOM CSV. If I supply `fileEncoding = UTF-8-BOM` to `read.csv` in base, this file comes in cleanly. Should `readr` be able to handle this?

This file is a MS SQL Server CSV export so...Windows. :wink:

**Comment by hadley** [comment]
Please supply a reproducible example - otherwise I can't test a solution.

**Comment by dgudmundsson** [comment]
I installed readr today from CRAN. It is awesome, but I had the same issue as davidski, I think... In my case it is a file with tab separated values. Symptom on my end was the first Column getting the BOM as part of its name, e.g. instead of first column having name "A" ends up with name "ï»¿A". Can't share the file in question (but it was a MS SQL Server export on Windows), but I made a small sample out of the same file using Notepad. This example shows the same issue I had with the file not touched by Notepad. I used the following to read the file: x <- read_tsv( "ReadrBOMTest.txt", col_names=TRUE, col_types=NULL, na="", skip=0, n_max=-1, progress=interactive() )

Until this is addressed I'll do a manual fix on the first column name. Thanks.

PS. I'm a first time commenter here on GitHub, don't see obvious way to provide the example file. Will figure out how to provide it, it should follow this comment very soon.

**Comment by hadley** [comment]
Thanks - that allowed me to create a simple example that doesn't rely on an external file:

``` r
x <- as.raw(c(0xef, 0xbb, 0xbf, 0x41, 0x09, 0x42, 0x0a, 0x30, 0x31, 0x09, 0x44))
rawToChar(x)
#> [1] "﻿A\tB\n01\tD"
read_tsv(x)
#> Source: local data frame [1 x 2]
#> 
#>        ﻿A     B
#>   (chr) (chr)
#> 1    01     D
```

You can see that the binary vector starts with the BOF (0xef, 0xbb, 0xbf), but it works fine for me. I think that implies that the problem is fixed in the dev version.

**Comment by wintwogonasty** [comment]
I'm still getting the byte order marker on my setup, and I'm running 0.2.2.9000.
Is it something to do with my locale?

```{r}

library(readr)

x <- as.raw(c(0xef, 0xbb, 0xbf, 0x41, 0x09, 0x42, 0x0a, 0x30, 0x31, 0x09, 0x44))
rawToChar(x)
#> [1] "ï»¿A\tB\n01\tD"
read_tsv(x)
#>  <U+FEFF>A B
#> 1        01 D
#>
sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readr_0.2.2.9000

loaded via a namespace (and not attached):
[1] tools_3.2.3 Rcpp_0.12.3
```

**Comment by stowdaniel** [comment]
I'm having a similar issue and it's causing problems reading in a group of .csvs I can read in with base read.csv  set to fileEncoding = UTF-8-BOM. 

> x <- as.raw(c(0xef, 0xbb, 0xbf, 0x41, 0x09, 0x42, 0x0a, 0x30, 0x31, 0x09, 0x44))
> rawToChar(x)
[1] "ï»¿A\tB\n01\tD"
> read_tsv(x)
Source: local data frame [1 x 2]

  <U+FEFF>A     B
      (chr) (chr)
1        01     D
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.3 tidyr_0.4.1 readr_0.2.2

loaded via a namespace (and not attached):
[1] magrittr_1.5   R6_2.1.2       assertthat_0.1 parallel_3.3.0 DBI_0.4-1     
[6] tools_3.3.0    Rcpp_0.12.4

**Comment by hadley** [comment]
Will need to figure out why this works for me, but not for other people. Probably windows.

**Comment by jimhester** [comment]
There are two separate issues here IMHO.

1. readr should not be including the BOM in the results.
``` r
x <- as.raw(c(0xef, 0xbb, 0xbf, 0x41, 0x09, 0x42, 0x0a, 0x30, 0x31, 0x09, 0x44))
x1 <- read_tsv(x)
charToRaw(names(x1)[1])
## this should not include the BOM and be only 41
#> [1] ef bb bf 41
```
2. R isn't handling the BOM properly in all cases on windows. (these examples run on windows VM)
``` r
x <- as.raw(c(0xef, 0xbb, 0xbf, 0x41, 0x09, 0x42, 0x0a, 0x30, 0x31, 0x09, 0x44))
x1 <- read_tsv(x)
## Fails if printing the data.frame
x1
#> <tibble [1 x 2]>
#>   <U+FEFF>A     B
#>       <chr> <chr>
#> 1        01     D
## Works fine if printing the names directory 
## (actually only true on the R console not in a reprex call/knitr).
names(x1)
#> [1] "<U+FEFF>A" "B"
## `format()` is the issue
format(names(x1))
#> [1] "<U+FEFF>A" "B        "
```
I think the problem is format calls the internal function [do_format()](https://github.com/wch/r-source/blob/2306686ab234eea993aa071ca54d54e01f6be3be/src/main/paste.c#L531), which calls [translateChar()](https://github.com/wch/r-source/blob/2306686ab234eea993aa071ca54d54e01f6be3be/src/main/sysutils.c#L911-L927). TranslateChar then calls [needsTranslation()](https://github.com/wch/r-source/blob/trunk/src/main/sysutils.c#L793-L807) which uses the utf8locale boolean to determine if UTF-8 characters need to be translated. [utf8locale](https://github.com/wch/r-source/blob/2306686ab234eea993aa071ca54d54e01f6be3be/src/main/platform.c#L241-L252) is set to false on windows, true on OS X. Windows uses UTF-16 for display, which is probably why the UTF-8 BOM gets converted to the UTF-16 exquivlent "\uFEFF"

Anyway I think the solution is readr should not be including the BOM the output data.frame.

**Comment by hadley** [comment]
@jimhester agreed - thanks for the exploration!
